/**
 * Engines verified to return results through the compatibility layer.
 * Anything not listed here is skipped on boot.
 */
export const SUPPORTED_SEARX_ENGINES: readonly string[] = [
  "360search_videos",
  "acfun",
  "ansa",
  "apple_maps",
  "artic",
  "artstation",
  "baidu",
  "bing_images",
  "bing_news",
  "bing_videos",
  "bitchute",
  "boardreader",
  "brave",
  "bt4g",
  "btdigg",
  "ccc_media",
  "chefkoch",
  "core",
  "crossref",
  "deezer",
  "demo_online",
  "docker_hub",
  "duckduckgo_definitions",
  "duckduckgo_web",
  "findfiles",
  "findthatmeme",
  "flickr_noapi",
  "frinkiac",
  "genius",
  "giphy",
  "github",
  "gmx",
  "goodreads",
  "google_cse",
  "google_images",
  "google_play",
  "grokipedia",
  "hackernews",
  "huggingface",
  "il_post",
  "imdb",
  "iqiyi",
  "jisho",
  "mastodon",
  "mediathekviewweb",
  "mediawiki",
  "microsoft_learn",
  "mixcloud",
  "mojeek",
  "mwmbl",
  "naver",
  "neocities",
  "openalex",
  "openlibrary",
  "openverse",
  "pexels",
  "photon",
  "picjumbo",
  "pinterest",
  "piratebay",
  "podchaser",
  "privacywall",
  "pubmed",
  "quark",
  "resulthunter",
  "rottentomatoes",
  "senscritique",
  "seznam",
  "sogou",
  "sogou_images",
  "sogou_videos",
  "sogou_wechat",
  "soundcloud",
  "stackexchange",
  "startpagina",
  "tagesschau",
  "translated",
  "wolframalpha_noapi",
  "yahoo_news",
  "youtube_noapi",
] as const;

const _supported = new Set<string>(SUPPORTED_SEARX_ENGINES);

const _extraEngines = (): string[] =>
  (process.env.DEGOOG_SEARX_EXTRA_ENGINES ?? "")
    .split(",")
    .map((code) => code.trim())
    .filter(Boolean);

export const isSupportedEngine = (engineCode: string): boolean =>
  _supported.has(engineCode) || _extraEngines().includes(engineCode);
